name: Deploy to Azure Web Apps
on:
  workflow_run:
    workflows: ['Docker Build and Push to Azure Container Registry']
    types:
      - completed

jobs:
  deploy:
    if: ${{github.event.workflow_run.conclusion=='success'}}
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        
        - name: Download Docker tag artifact
          uses: actions/download-artifact@v4
          with:
            name: docker-tag
            path: .
            github-token: ${{ github.token }}
            repository: ${{ github.repository }}
            run-id: ${{ github.event.workflow_run.id }}
          
        - name: Read Docker tag
          id: read_tag
          run: |
             TAG=$(cat docker_tag.txt)
             echo "docker_tag=$TAG" >> $GITHUB_OUTPUT
        - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{secrets.AZURE_CREDENTIALS}}    

        - name: Deployment to Azure Web Apps 
          uses: azure/webapps-deploy@v2
          with:
            app-name: llmchatwebapp
            images: ${{ steps.read_tag.outputs.docker_tag }}
          env:
            GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
            HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
 




    
